/**
 * Ways To — shared deck content for the vintage slot machine.
 * Loaded before vintage-slot-machine.js
 */
(function (global) {
    "use strict";

    global.WAYSTO_DECKS = {
        waysTo: [
            "Address conflicts",
            "Appear more fashionable",
            "Be healthier",
            "Become famous",
            "Build a home",
            "Catch mice",
            "Clean the house",
            "Clean their teeth",
            "Compost at home",
            "Create community",
            "Curate a style",
            "Cure boredom",
            "Cure dopamine addiction",
            "Declutter a phone",
            "Decongest traffic",
            "Develop new talent",
            "Disconnect from social media",
            "Dispose of waste",
            "Divide chores",
            "Document memories",
            "Drive social change",
            "Eat more balanced",
            "Eat on the go",
            "Exercise more",
            "Exercise with no gym",
            "Explore locally",
            "Feed hungry teens",
            "Feel younger",
            "Fight crime",
            "Find a new hobby",
            "Find new foods",
            "Find new movies",
            "Get people outside",
            "Get to school",
            "Improve boring commutes",
            "Improve communication of large companies",
            "Improve cross-country transit",
            "Improve eloquence",
            "Keep their hands warm",
            "Kill bugs",
            "Learn a new language",
            "Learn an instrument",
            "Learn more about nature",
            "Learn to swim",
            "Make cooking easier",
            "Make eating more fun",
            "Make first dates less awkward",
            "Make friends",
            "Make moving less stressful",
            "Make music",
            "Make new friends",
            "Make side cash",
            "Manage time",
            "Meal prep",
            "Pay attention to health",
            "Physically connect long distance relationships",
            "Promote local events",
            "Quit bad habits",
            "Read more",
            "Reduce food waste",
            "Reinvent play parks",
            "Reward small achievements",
            "Save money",
            "Save the whales",
            "Save water",
            "Say goodbye",
            "Search for places to live",
            "Settle a dispute",
            "Share ideas",
            "Show gratitude",
            "Show someone you care",
            "Sit up straight",
            "Spend money",
            "Spread ideas",
            "Teach children",
            "Tell someone you care",
            "Train animals",
            "Travel cheaply",
            "Travel without knowing the language",
            "Wake up early",
        ],

        users: [
            "Grumpy old man",
            "Acrobats",
            "Angry old men",
            "Couch surfer",
            "Skateboarders",
            "Bee keeper",
            "Struggling new actor",
            "Fast food worker",
            "Middle school robotics members",
            "Retiree",
            "Private school girl",
            "Fresh college graduate",
            "Construction workers",
            "Garage-band member",
            "Cowgirls",
            "Tech bro",
            "Pilots",
            "Frequent first class flyers",
            "Critics",
            "Disney adults",
            "Secret agent",
            "House flipper",
            "Extreme sports athlete",
            "Doomsday peppers",
            "Firefighters",
            "Foster parents",
            "Competitive gamer",
            "Deep sea diver",
            "Girlfriends",
            "Horse girls",
            "Comic book collector",
            "Country club golfer",
            "Local social media influencer",
            "Outdoor enthusiasts",
            "Janitors",
            "Middle aged women",
            "Hippies",
            "Rock climbing enthusiast",
            "Starving artist",
            "Morticians",
            "Stay at home dad",
            "Dating app addict",
            "Knitting addict",
            "Budget backpackers",
            "Cruise ship staff",
            "Rockstars",
            "Gamers",
            "Primary school teachers",
            "Bus drivers",
            "School teachers",
            "Stoners",
            "Pilates connoisseur",
            "Single moms",
            "Farmers",
            "Traffic cops",
            "Unemployed",
            "Van-life nomads",
            "Young CEOs",
            "Busy barista",
            "Overworked summer intern",
            "Reading enthusiast",
            "Airbnb hosts",
            "City commuters",
            "Coffee connoisseur",
            "College students",
            "Crazy cat ladies",
            "High school athletes",
            "Homebody",
            "Midlife crisis fathers",
            "Raver",
            "Rural farmers",
            "Weight lifters",
        ],

        designLimit: [
            "Artistic",
            "As soft as a feather",
            "Biodegradable",
            "Collapsible",
            "Collectible",
            "Covered in mushrooms",
            "Cozy",
            "Customizable",
            "Feels like a game",
            "Can go off grid",
            "Fragile",
            "Has a hidden feature",
            "Glow in the dark",
            "Works in space",
            "Relies on randomness",
            "Inflatable",
            "Lighter than a brick",
            "Made from paper",
            "Builds a habit",
            "Sellable in vending machine",
            "Uses no personal data",
            "Made out of glass",
            "Magnetic",
            "Pocket-sized",
            "Child friendly",
            "Non flammable",
            "Subscription based",
            "Grows over time",
            "Involves at least 2 people",
            "Off the grid",
            "Only lives in the cloud",
            "Organic",
            "Recyclable",
            "Requires ticket",
            "Is a pop-up",
            "Works differently every use",
            "Single use",
            "Needs certification",
            "Is collectable",
            "Easy to clean",
            "Synced with the cloud",
            "Is totally silent",
            "Is controlled entirely by voice",
            "Under $10",
            "Uses no power",
            "Very European",
            "Wearable",
            "Works on the moon",
            "Minty fresh",
            "Responsive",
            "Something your mother would hate",
            "Trendy",
            "Unbreakable",
            "Autonomous",
            "Edible",
            "Entertaining",
            "Evil",
            "Growing",
            "Saves time",
            "Links physical and digital products",
            "Powered — not digital",
            "Uses no electricity",
            "Solar powered",
            "Non physical",
        ],

        audienceLimit: [
            "Only buys faux designer",
            "Cares about status",
            "Conspiracy minded",
            "Constantly multitasking",
            "Craves routine",
            "Early adopter (seeks innovation)",
            "Easily distracted",
            "Incredibly lazy",
            "Lives alone",
            "Obsessed with nostalgia",
            "Risk averse",
            "Seeks competitive environment",
            "Has quiet hours",
            "Tech evangelist",
            "Travels often",
            "Trend follower",
            "Is incredibly competitive",
            "Gets bored in 30 seconds",
            "Refuses to wait",
            "Resists change",
            "Follows trends",
            "Prefers experiences over materialism",
            "Hardcore budgets",
            "Is a minimalist",
            "Lives in desolate area",
            "Loves to break rules",
            "Is very secretive",
            "Craves community",
            "Gets easily distracted",
            "Is an early adopter",
            "Is chronically online",
            "Is a maximalist",
            "Only believes in astrology",
            "Is dramatic",
            "Chronically online",
            "Minimalist",
            "Needs instant gratification",
            "Needs structure and rules",
            "Prefers handmade items",
            "Is incredibly serious",
            "Likes being alone",
        ],

        constraintsPlus: [
            "Feels like a fantasy quest",
            "A jester could use it",
            "Is music based",
            "Can be used in an apocalypse",
            "Requires two strangers to use",
            "Utilizes puzzles",
            "Has a secret unlockable feature",
            "Connects to the body",
            "Is only usable at night",
            "Resembles a stuffed animal",
            "Is futuristic",
            "Uses AR",
            "Can be used with VR",
            "Requires customization",
            "A medieval peasant could use it",
            "Can be used in space",
            "Resembles artwork",
            "Can be used in a library",
            "Went out of style 30 years ago",
            "Uses a hologram",
            "Is turn-based",
            "Is cinematic",
            "Is buildable",
            "Has some sort of feedback",
            "Picture-based",
            "Can be hidden/disguised",
            "Doesn't require touch",
            "Is mission based",
            "Utilizes geolocation",
            "Could be a weapon",
            "Feels nostalgic",
            "Can be rented",
            "Has physical feedback",
            "Glows in the dark",
            "Tracks motion",
            "Can be layered",
            "Is commanded through voice",
            "Looks like a plant",
            "Uses astrology",
            "Works in a plane",
            "Uses treasure hunting",
            "Has a point system",
            "Works by itself",
            "Resembles a sound board",
        ],
    };
})(typeof window !== "undefined" ? window : globalThis);
